### ISSUE TITLE
CCNA Trivia - /30 Subnet Between Two Routes Question

### ISSUE THREAD

**Issue by Null-Sound** [ChristopherJHart/discord-it-trivia#9]
The question is "An engineer must configure a /30 subnet between two routes. Which usable IP address and subnet mask combination meets this criteria?"

Two valid choices are given:
1. interface e0/0 description to XX-AXXX:XXXXX ip address 209.165.201.2 225.255.255.252
2. interface e0/0 description to XX-AXXX:XXXXX ip address 10.2.1.3 255.255.255.252

However, it said the 1st choice was correct. The question needs to clarify whether the subnet is public or private.

**Comment by ChristopherJHart** [comment]
Hello!

This issue references the following question:
```yaml
    - prompt: >-
        An engineer must configure a /30 subnet between two routes. Which
        usable IP address and subnet mask combination meets this criteria?
      type: "multiple choice"
      correct_choice: 4
      choices:
        - id: 1
          text: >-
            interface e0/0 description to XX-AXXX:XXXXX ip address 10.2.1.3
            255.255.255.252
        - id: 2
          text: >-
            interface e0/0 description to XX-AXXX:XXXXX ip address 192.168.1.1
            255.255.255.248
        - id: 3
          text: >-
            interface e0/0 description to XX-AXXX:XXXXX ip address 172.16.1.4
            255.255.255.248
        - id: 4
          text: >-
            interface e0/0 description to XX-AXXX:XXXXX ip address
            209.165.201.2 225.255.255.252
      tags:
        - Subnetting
        - Network Fundamentals
```
Answer choice 4 is intended to be the correct answer, but is not technically correct at the moment because an invalid subnet mask of `225.255.255.252` is used. Answer choice 4 should be corrected to use a subnet mask of `255.255.255.252`. I can fix this shortly through this issue.

Answer choice 1 (which you referenced) is not a valid answer to this question, as 10.2.1.3 is the broadcast address of the 10.2.1.0/30 subnet. Within this subnet, the usable IP addresses are 10.2.1.1 and 10.2.1.2 - you cannot (or at least, should not) be able to assign an IP address of 10.2.1.3 to a network interface with a subnet mask of 255.255.255.252.

Let me know if you have any questions!

-Christopher
